# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

defaults: &defaults
  docker:
    - image: circleci/ruby:2.6.0
      environment:
        BUNDLER_VERSION: 2.0.2
  # environment:
  #   LC_ALL: en_US.UTF-8 # required by Fastlane
  #   LANG: en_US.UTF-8 # required by Fastlane
  # shell: /bin/bash --login -eo pipefail # required for custom Ruby version

aliases:

  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
  - &restore_bundle_cache
    restore_cache:
      keys:
        - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        - rails-demo-bundle-v2-

  - &bundle_install
    run:
      name: Bundle install
      command: bundle check --path vendor/bundle || bundle install --deployment

  - &save_bundle_cache
    save_cache:
      key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

jobs:
  kickoff_release:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - *restore_bundle_cache
      - *bundle_install
      - *save_bundle_cache
      - run: fastlane release kickoff:true

  release:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - *restore_bundle_cache
      - *bundle_install
      - *save_bundle_cache
      - run: fastlane release

  test:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - *restore_bundle_cache
      - *bundle_install
      - *save_bundle_cache
      - run: fastlane test

workflows:
  version: 2
  test:
    jobs:
      - test