# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test do |options|
    UI.important("I'm Testing!!")
    UI.important("options passed: #{options}")
  end

  lane :release do |options|
    if is_ci
      options[:is_hotfix] = options[:is_hotfix] || ENV["is_hotfix"]
      options[:is_test] = options[:is_test] || ENV["is_test"]
      if options[:kickoff]
        kickoff_release(options)
      else
        deploy_release(options)
      end
    elsif options[:local_test]
      options[:is_test] = true
      kickoff_release(options)
    else
      trigger_release(options)
    end
  end

  private_lane :trigger_release do |options|
    release_branch = options[:is_test] ? "test-release" : "release"
    is_test = options[:is_test]
    is_hotfix = options[:is_hotfix]
    ci(circle_job: "kickoff_release", branch: release_branch, options: options)
  end

  private_lane :kickoff_release do |options|
    #required env var
    if !ENV["CHANGELOG_GITHUB_TOKEN"]
      UI.user_error! "env var CHANGELOG_GITHUB_TOKEN is not set, but it's required to deploy a release."
      return
    end

    ensure_git_status_clean

    if options[:is_test]
      base_branch = "test-develop"
      release_branch = "test-release"

      UI.important "Test release using base-branch: \"#{base_branch}\", release-branch: \"#{release_branch}\"."
    else
      base_branch = "develop"
      release_branch = "release"
    end

    sh("git checkout " + release_branch)

    unless options[:is_hotfix]
      # merge develop (base_branch) into the release branch
      sh("git merge origin/" + base_branch)
    end

    # Create a version bump commit on release
    current_version = File.read('../versionfile.txt')
    major = current_version.split(".")[0].to_i

    if options[:is_hotfix]
      minor = current_version.split(".")[1].to_i
      next_version = "#{major}.#{minor + 1}"
    else
      next_version = "#{major + 1}.0"
    end

    open('../versionfile.txt', 'w') do |f|
      f.puts next_version
    end

    git_commit(path: ".", message: "Version bump")
    push_to_git_remote

    # Add a tag to the version bump commit
    git_tag_name = next_version + "-Release"
    if options[:is_test]
      UI.message("If not testing, would add a git tag \"#{git_tag_name}\" now")
    else
      prune_git_tags
      add_git_tag(tag: git_tag_name)
      push_to_git_remote
    end

    job_name = "release"

    UI.important("will trigger CI job #{job_name} for branch #{release_branch}")
    ci(circle_job: job_name, branch: release_branch, options: options)

    # Create a Github release
    # TODO fix with env var
    # add_github_release(new: next_version, prev: current_version, is_dry_run: options[:is_test])

    # Merge release branch into base branch (develop unless it's a test release)
    sh("git checkout " + base_branch)
    git_pull

    begin
      sh("git merge " + release_branch)
    rescue => exception
      UI.important "Git merge failed while merging release-branch: \"#{release_branch}\" into base-branch: \"#{base_branch}\"\nException: #{exception}"
      UI.important "This conflict needs to be solved manually, I'll create a PR for you to start"
    else
      push_to_git_remote
    end
  end

  private_lane :deploy_release do |options|
    UI.important("I'm releasing!!")
    UI.important("options passed: #{options}")
  end

  desc "Prunes all local tags that are not in sync with tags on origin"
  private_lane :prune_git_tags do
    sh("git tag -d $(git tag)")
    sh("git fetch --tags")
  end

  desc "Adds github release. NOTE: It is required to generate a GH personal token and store it in env(put it in ~/.bash_profile) under CHANGELOG_GITHUB_TOKEN key"
  private_lane :add_github_release do |options|
    is_dry_run = options[:is_dry_run]
    # If it's a dry run, we don't have a tag to compare against, so we'll use HEAD instead.
    next_version_tag_name = is_dry_run ? "HEAD" : options[:new] + "-Release"
    current_version_tag_name = options[:prev] + "-Release"

    changelog = changelog_from_git_commits(between: [current_version_tag_name, next_version_tag_name], pretty: "- %s", merge_commit_filtering: "exclude_merges")

    current_version = options[:new]
    release_name = "#{current_version}-Release"

    if is_dry_run
      UI.important("If not testing, would create Github release with following changelog: \n#{changelog}\nname: \"#{release_name}\"")
    else
      set_github_release(repository_name: "mvandervelden/test-ci", name: release_name, tag_name: next_version_tag_name, description: "Changelog:\n#{changelog}", api_token: ENV["CHANGELOG_GITHUB_TOKEN"])
    end
  end

  lane :tmp_gh_release do
    set_github_release(repository_name: "mvandervelden/test-ci", name: "Test", tag_name: "8.0-Release", description: "Changelog:\nTest", api_token: ENV["CHANGELOG_GITHUB_TOKEN"])
  end
end
